---
- name: backend server configuration
  hosts: backend
  become: yes

  roles:
    - common
    - backend

- name: web server cofiguration
  hosts: backend
  become: yes

  roles:
    - common
    - web
